# Formules Statistiek I

::: {.content-visible when-format="html"}
::: callout-tip
Om een formule te kopiëren naar MS Word klik je met de rechtermuisknop op de formule en kies 'Copy to clipboard ... MathML Code'. Gebruik daarna CTRL/CMD+V om de formule te plakken.

Om een formule te kopiëren naar een RMarkdown document, klik met de rechtermuisknop op de formule en kies 'Copy to clipboard ... TeX Commands'. In Rstudio Visual Markdown Editor kies Insert ... Latex Math ... Display Math en daarna CTRL/CMD+V om de formule te plakken.
:::
:::

## Beschrijvende statistieken

### Gemiddelde (*Mean*)

$$\bar{x} = \frac{\sum_{i = 1}^{n}x_{i}}{n}$$

### Variantie (*Variance*)

$$s^{2} = \frac{\sum_{i = 1}^{n}{(x_{i} - \bar{x})}^{2}}{N - 1}$$

### Standaardafwijking (*Standard deviation*)

$$s = \sqrt{s^{2}}$$

### Interkwartielafstand (*Interquartile range*)

$$IQR = \ Q_{3} - Q_{1}$$

### Verwachte waarde van een discrete stochastische variabele (*Expected Value of a Discrete Random Variable*)

$$E(X) = \ \sum_{i = 1}^{k}{x_{i}P(X = x_{i})}$$

### Algemene Formule voor de Variantie (*General Variance Formula*)

$$\sigma^{2} = \sum_{j = 1}^{k}{{(x_{j} - \mu)}^{2}P(X = x_{j})}$$

## Kansrekening

### Kans op gebeurtenis A (*Probability of event A*)

$$
P(A)
$$

### Intersectie van gebeurtenissen (*Intersection of events*)

$$
P(A \cap B) = P(\text{A and B})
$$

### Vereniging van gebeurtenissen (*Union of events*)

$$
P(A \cup B) = P(\text{A or B})
$$

### Algemene somregel (*General addition rule*)

$$P(A\ or\ B) = P(A) + P(B) - P(A\ and\ B)$$

### Voorwaardelijke kans (*Conditional probability*)

$$P\left( A \middle| B \right) = \ \frac{P(A\ and\ B)}{P(B)}$$

### Algemene productregel (*General multiplication rule*)

$$P(A\ and\ B) = P\left( A \middle| B \right)*P(B)$$

## Normaalverdeling

### Z-score

$$z = \frac{x - \mu}{\sigma}$$

## Proporties

### Betrouwbaarheidsinterval 1 proportie (*Confidence interval 1 proportion*)

$$CI = \ \hat{p}\  \pm z^{*}SE\left( \hat{p} \right)$$

$$SE\left( \hat{p} \right) = \sqrt{\frac{\hat{p}(1 - \hat{p})}{N}}$$

### Hypothesetoets 1 proportie (*Hypothesis test 1 proportion*)

$$Z = \ \frac{\hat{p} - p_{0}}{SE}$$

$$SE\left( p_{0} \right) = \sqrt{\frac{p_{0}(1 - p_{0})}{N}}$$

### Betrouwbaarheidsinterval 2 onafhankelijke proporties (*Confidence interval 2 independent proportions*)

$$CI = {(\hat{p}}_{1} - {\hat{p}}_{2}) \pm z^{*}SE\left( {\hat{p}}_{1} - {\hat{p}}_{2} \right)$$

$$SE\left( {\hat{p}}_{1} - {\hat{p}}_{2} \right) = \sqrt{\frac{{\hat{p}}_{1}\left( 1 - {\hat{p}}_{1} \right)}{n_{1}} + \frac{{\hat{p}}_{2}(1 - {\hat{p}}_{2})}{n_{2}}}$$

### Hypothesetoets 2 onafhankelijke proporties (*Hypothesis test 2 independent proportions*)

$$Z = \ \frac{\left( {\hat{p}}_{1} - {\hat{p}}_{2} \right) - \text{null value}}{SE}$$

$${\hat{p}}_{pooled} = \frac{{\hat{p}}_{1}n_{1} + {\hat{p}}_{2}n_{2}}{n_{1} + n_{2}}$$

$$SE = \sqrt{\frac{{\hat{p}}_{pooled}(1 - {\hat{p}}_{pooled})}{n_{1}} + \frac{{\hat{p}}_{pooled}(1 - {\hat{p}}_{pooled})}{n_{2}}}$$

## Chikwadraat en associatiematen

### Chi^2^ ($\chi^{2}$) one-way

$$\chi^{2} = \sum_{i = 1}^{k}\frac{{(O_{i} - E_{i})}^{2}}{E_{i}}$$

$$df = k - 1$$

### Chi^2^ ($\chi^{2}$) two-way

$$ E_{i,j} = \frac{kolomtotaal_j * rijtotaal_i}{tabeltotaal} $$

$$\chi^{2} = \sum_{i,\ j}^{}\frac{{(O_{i,j} - E_{i,j})}^{2}}{E_{i,j}}$$

$$ df = (R-1)(C-1) $$

### Phi ($\phi$)

$$\phi = \sqrt{\frac{\chi^{2}}{N}}$$

### Cramérs V

$$V = \sqrt{\frac{\chi^{2}}{N*(Min.\ van\ r - 1,\ c - 1)}}$$

### Lambda ($\lambda)$

$$\lambda = \frac{E1 - E2}{E1} = \frac{\text{original error} - \text{remaining error}}{\text{original error}}$$

### Gamma ($\gamma)$

$$\gamma = \frac{N_{s} - N_{d}}{N_{s} + N_{d}}$$

## Betrouwbaarheidsinterval gemiddelde en t-toets

### Standaardfout van het gemiddelde (*Standard error of the mean*)

$$SE = \frac{s}{\sqrt{N}}$$

### Betrouwbaarheidsinterval gemiddelde (*Confidence interval mean*)

$$CI = \bar{x} \pm t_{df}^{*}*SE$$

### *t* (enkele steekproef / *one sample*)

$$t = \frac{\bar{x} - \mu_{0}}{s/\sqrt{N}}$$

$$ df = n - 1 $$

### *t* (gepaarde steekproeven/*paired samples*)

$$t = \frac{{\bar{x}}_{diff} - \mu_{diff}}{s_{diff}/\sqrt{n_{diff}}}$$

$$ df = n - 1 $$

### *Welch's t-test* (onafhankelijke steekproeven/ *independent samples*)

$$t = \frac{{(\bar{X}}_{1} - {\bar{X}}_{2}) - (\mu_{1} - \mu_{2})}{SE}$$

$$SE = \ \sqrt{\frac{s_{1}^{2}}{n_{1}} + \frac{s_{2}^{2}}{n_{2}}}$$

### Cohen's D (one sample)

$$d = \frac{\bar{X} - \mu_{0}}{s}$$

### Cohen's D (gepaard/*paired*)

$$d = \frac{\bar{D} - \mu_{0}}{s}$$

## ANOVA

### Som en gemiddelde van kwadraten tussen groepen (*Sum and Mean Square between Groups*)

$$MSG = \frac{SSG}{{df}_{G}}$$

$$SSG = \sum_{i=1}^{k}{n_{i}{({\bar{x}}_{i} - {\bar{x}}_{grand})}^{2}}$$

$$\text{df}_{G} = k - 1$$

### Som en gemiddelde kwadratische fout (*Sum of squared error & mean squared error*)

$$MSE = \frac{SSE}{{df}_{E}}$$

$$SSE = \sum_{}^{}{(x_{ik} - {\bar{x}}_{k})}^{2}$$

$${df}_{E} = n\ –k$$

### F (ANOVA)

$$F = \frac{MSG}{MSE}$$
